AWSTemplateFormatVersion: 2010-09-09
Description: Example Table

Resources:
  MySecretA:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: dev/rmq/rabbit/admin
      Description: "Secrets for rabbit instance"
      GenerateSecretString:
        SecretStringTemplate: '{"username": "rabbit"}'
        GenerateStringKey: "password"
        PasswordLength: 15
        ExcludeCharacters: '"@/\=:,'