AWSTemplateFormatVersion: '2010-09-09'
Description: Template for SQS without subscription.
Parameters:
  Environment:
    Description: Environment
    Default: dev
    Type: String
  TeamName:
    Description: Name of the team responsible
    Type: String
    Default: Team-Settlement
  QueueName:
    Description: Queue name
    Default: demo_queue
    Type: String
  DelaySeconds:
    Description: The time in seconds for which the delivery of all messages in the queue is delayed. You can specify an integer value of 0 to 900 (15 minutes). The default value is 0.
    Type: Number
    Default: 60
  FifoQueue:
    Description: Specifies a FIFO queue type
    Type: String
    Default: false
  ContentBasedDeduplication:
    Description: For first-in-first-out (FIFO) queues, specifies whether to enable content-based deduplication. During the deduplication interval, Amazon SQS treats messages that are sent with identical content as duplicates and delivers only one copy of the message.
    Type: String
    Default: false
Conditions:
  IsFifo: !Equals
    - !Ref FifoQueue
    - true

Resources:
  ApSQSDeadLetter:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !If [IsFifo, !Sub "${Environment}_${QueueName}_dead_letter_queue.fifo", !Sub "${Environment}_${QueueName}_dead_letter_queue"]
      FifoQueue: !If [IsFifo, !Ref FifoQueue, !Ref AWS::NoValue]
      ContentBasedDeduplication: !If [IsFifo, !Ref ContentBasedDeduplication, !Ref AWS::NoValue]
      Tags:
        - Key: Env
          Value: !Ref Environment
        - Key: Owner
          Value: !Ref TeamName
  ApSQS:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !If [IsFifo, !Sub "${Environment}_${QueueName}_queue.fifo", !Sub "${Environment}_${QueueName}_queue"]
      FifoQueue: !If [IsFifo, !Ref FifoQueue, !Ref AWS::NoValue]
      ContentBasedDeduplication: !If [IsFifo, !Ref ContentBasedDeduplication, !Ref AWS::NoValue]
      DelaySeconds: !Ref DelaySeconds
      VisibilityTimeout: 300
      MessageRetentionPeriod: 86400
      ReceiveMessageWaitTimeSeconds: 20
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt ApSQSDeadLetter.Arn
        maxReceiveCount: 3
      Tags:
        - Key: Env
          Value: !Ref Environment
        - Key: Owner
          Value: !Ref TeamName